import type { Metadata } from 'next'
import { AlertTriangle } from 'lucide-react'
import { LegalLayout, LegalSection } from '@/components/legal/LegalLayout'
import { siteConfig } from '@/lib/siteConfig'

export const metadata: Metadata = {
  title: 'Disclaimer',
  description: `Important disclaimers regarding use of ${siteConfig.name}.`,
}

export default function DisclaimerPage() {
  return (
    <LegalLayout title="Disclaimer" updated="July 26, 2026" icon={<AlertTriangle size={13} />}>
      <LegalSection title="1. No Professional Advice">
        <p>
          Content generated by AI agents built on {siteConfig.name} — including AI Chat, the AI Business
          Advisor, AI Customer Insights, and AI Calls — is produced using Google Gemini and automated
          workflows. It is provided for informational purposes only and does not constitute legal, medical,
          financial, or other professional advice, including any recommendations surfaced by the AI Business
          Advisor.
        </p>
      </LegalSection>

      <LegalSection title="2. AI-Generated Content">
        <p>
          AI models, including Google Gemini, can produce inaccurate, incomplete, or biased output. You are
          responsible for reviewing and validating any AI-generated content — chat replies, business
          recommendations, customer insights, or call responses — before relying on it or presenting it to end
          users or customers. See our <a href="/legal/ai-usage">AI Usage &amp; Limitations</a> page for more detail.
        </p>
      </LegalSection>

      <LegalSection title="3. Service Availability">
        <p>
          We strive for high availability but do not guarantee uninterrupted or error-free operation of the
          Service. Scheduled maintenance, third-party outages, or unforeseen issues may affect availability.
        </p>
      </LegalSection>

      <LegalSection title="4. Third-Party Links & Integrations">
        <p>
          The Service may link to or integrate with third-party websites and services. We are not responsible
          for the content, accuracy, or practices of any third party.
        </p>
      </LegalSection>

      <LegalSection title="5. Limitation of Liability">
        <p>
          To the fullest extent permitted by law, {siteConfig.name} disclaims liability for any loss or damage
          arising from reliance on information or AI-generated output produced through the Service. See our{' '}
          <a href="/legal/terms">Terms &amp; Conditions</a> for the complete limitation of liability.
        </p>
      </LegalSection>
    </LegalLayout>
  )
}
